// Generated by gencpp from file cartesian_control_msgs/CartesianTrajectory.msg
// DO NOT EDIT!


#ifndef CARTESIAN_CONTROL_MSGS_MESSAGE_CARTESIANTRAJECTORY_H
#define CARTESIAN_CONTROL_MSGS_MESSAGE_CARTESIANTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cartesian_control_msgs/CartesianTrajectoryPoint.h>

namespace cartesian_control_msgs
{
template <class ContainerAllocator>
struct CartesianTrajectory_
{
  typedef CartesianTrajectory_<ContainerAllocator> Type;

  CartesianTrajectory_()
    : header()
    , points()
    , controlled_frame()  {
    }
  CartesianTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)
    , controlled_frame(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _controlled_frame_type;
  _controlled_frame_type controlled_frame;





  typedef boost::shared_ptr< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianTrajectory_

typedef ::cartesian_control_msgs::CartesianTrajectory_<std::allocator<void> > CartesianTrajectory;

typedef boost::shared_ptr< ::cartesian_control_msgs::CartesianTrajectory > CartesianTrajectoryPtr;
typedef boost::shared_ptr< ::cartesian_control_msgs::CartesianTrajectory const> CartesianTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator1> & lhs, const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points &&
    lhs.controlled_frame == rhs.controlled_frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator1> & lhs, const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cartesian_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe1b5791fdbc25aca5939664297d26be";
  }

  static const char* value(const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe1b5791fdbc25acULL;
  static const uint64_t static_value2 = 0xa5939664297d26beULL;
};

template<class ContainerAllocator>
struct DataType< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartesian_control_msgs/CartesianTrajectory";
  }

  static const char* value(const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# header.frame_id is the frame in which all data from CartesianTrajectoryPoint[] is given\n"
"Header header\n"
"CartesianTrajectoryPoint[] points\n"
"string controlled_frame\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cartesian_control_msgs/CartesianTrajectoryPoint\n"
"duration time_from_start\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist twist\n"
"geometry_msgs/Accel acceleration\n"
"# A more suitable datatype would be good, see https://github.com/ros/common_msgs/issues/137\n"
"geometry_msgs/Accel jerk\n"
"CartesianPosture posture\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: cartesian_control_msgs/CartesianPosture\n"
"# Posture joint names may reflect a subset of all available joints (empty posture definitions are\n"
"# also possible). The length of posture_joint_names and posture_joint_values have to be equal.\n"
"\n"
"string[] posture_joint_names\n"
"float64[] posture_joint_values\n"
;
  }

  static const char* value(const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
      stream.next(m.controlled_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "controlled_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.controlled_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTESIAN_CONTROL_MSGS_MESSAGE_CARTESIANTRAJECTORY_H
