// Generated by gencpp from file cartesian_control_msgs/FollowCartesianTrajectoryGoal.msg
// DO NOT EDIT!


#ifndef CARTESIAN_CONTROL_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYGOAL_H
#define CARTESIAN_CONTROL_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cartesian_control_msgs/CartesianTrajectory.h>
#include <cartesian_control_msgs/CartesianTolerance.h>
#include <cartesian_control_msgs/CartesianTolerance.h>

namespace cartesian_control_msgs
{
template <class ContainerAllocator>
struct FollowCartesianTrajectoryGoal_
{
  typedef FollowCartesianTrajectoryGoal_<ContainerAllocator> Type;

  FollowCartesianTrajectoryGoal_()
    : trajectory()
    , path_tolerance()
    , goal_tolerance()
    , goal_time_tolerance()  {
    }
  FollowCartesianTrajectoryGoal_(const ContainerAllocator& _alloc)
    : trajectory(_alloc)
    , path_tolerance(_alloc)
    , goal_tolerance(_alloc)
    , goal_time_tolerance()  {
  (void)_alloc;
    }



   typedef  ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;

   typedef  ::cartesian_control_msgs::CartesianTolerance_<ContainerAllocator>  _path_tolerance_type;
  _path_tolerance_type path_tolerance;

   typedef  ::cartesian_control_msgs::CartesianTolerance_<ContainerAllocator>  _goal_tolerance_type;
  _goal_tolerance_type goal_tolerance;

   typedef ros::Duration _goal_time_tolerance_type;
  _goal_time_tolerance_type goal_time_tolerance;





  typedef boost::shared_ptr< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FollowCartesianTrajectoryGoal_

typedef ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<std::allocator<void> > FollowCartesianTrajectoryGoal;

typedef boost::shared_ptr< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal > FollowCartesianTrajectoryGoalPtr;
typedef boost::shared_ptr< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal const> FollowCartesianTrajectoryGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator1> & lhs, const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator2> & rhs)
{
  return lhs.trajectory == rhs.trajectory &&
    lhs.path_tolerance == rhs.path_tolerance &&
    lhs.goal_tolerance == rhs.goal_tolerance &&
    lhs.goal_time_tolerance == rhs.goal_time_tolerance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator1> & lhs, const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cartesian_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53c6564a309cf1d1f2d2c4e0478a40b3";
  }

  static const char* value(const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53c6564a309cf1d1ULL;
  static const uint64_t static_value2 = 0xf2d2c4e0478a40b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartesian_control_msgs/FollowCartesianTrajectoryGoal";
  }

  static const char* value(const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"CartesianTrajectory trajectory\n"
"CartesianTolerance path_tolerance\n"
"CartesianTolerance goal_tolerance\n"
"duration goal_time_tolerance\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cartesian_control_msgs/CartesianTrajectory\n"
"# header.frame_id is the frame in which all data from CartesianTrajectoryPoint[] is given\n"
"Header header\n"
"CartesianTrajectoryPoint[] points\n"
"string controlled_frame\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cartesian_control_msgs/CartesianTrajectoryPoint\n"
"duration time_from_start\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist twist\n"
"geometry_msgs/Accel acceleration\n"
"# A more suitable datatype would be good, see https://github.com/ros/common_msgs/issues/137\n"
"geometry_msgs/Accel jerk\n"
"CartesianPosture posture\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: cartesian_control_msgs/CartesianPosture\n"
"# Posture joint names may reflect a subset of all available joints (empty posture definitions are\n"
"# also possible). The length of posture_joint_names and posture_joint_values have to be equal.\n"
"\n"
"string[] posture_joint_names\n"
"float64[] posture_joint_values\n"
"\n"
"================================================================================\n"
"MSG: cartesian_control_msgs/CartesianTolerance\n"
"geometry_msgs/Vector3 position_error\n"
"geometry_msgs/Vector3 orientation_error\n"
"geometry_msgs/Twist twist_error\n"
"geometry_msgs/Accel acceleration_error\n"
;
  }

  static const char* value(const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory);
      stream.next(m.path_tolerance);
      stream.next(m.goal_tolerance);
      stream.next(m.goal_time_tolerance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowCartesianTrajectoryGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartesian_control_msgs::FollowCartesianTrajectoryGoal_<ContainerAllocator>& v)
  {
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::cartesian_control_msgs::CartesianTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
    s << indent << "path_tolerance: ";
    s << std::endl;
    Printer< ::cartesian_control_msgs::CartesianTolerance_<ContainerAllocator> >::stream(s, indent + "  ", v.path_tolerance);
    s << indent << "goal_tolerance: ";
    s << std::endl;
    Printer< ::cartesian_control_msgs::CartesianTolerance_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_tolerance);
    s << indent << "goal_time_tolerance: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.goal_time_tolerance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTESIAN_CONTROL_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYGOAL_H
