// Generated by gencpp from file cartesian_control_msgs/FollowCartesianTrajectoryFeedback.msg
// DO NOT EDIT!


#ifndef CARTESIAN_CONTROL_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYFEEDBACK_H
#define CARTESIAN_CONTROL_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cartesian_control_msgs/CartesianTrajectoryPoint.h>
#include <cartesian_control_msgs/CartesianTrajectoryPoint.h>
#include <cartesian_control_msgs/CartesianTrajectoryPoint.h>

namespace cartesian_control_msgs
{
template <class ContainerAllocator>
struct FollowCartesianTrajectoryFeedback_
{
  typedef FollowCartesianTrajectoryFeedback_<ContainerAllocator> Type;

  FollowCartesianTrajectoryFeedback_()
    : header()
    , controlled_frame()
    , desired()
    , actual()
    , error()  {
    }
  FollowCartesianTrajectoryFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , controlled_frame(_alloc)
    , desired(_alloc)
    , actual(_alloc)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _controlled_frame_type;
  _controlled_frame_type controlled_frame;

   typedef  ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator>  _desired_type;
  _desired_type desired;

   typedef  ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator>  _actual_type;
  _actual_type actual;

   typedef  ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator>  _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FollowCartesianTrajectoryFeedback_

typedef ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<std::allocator<void> > FollowCartesianTrajectoryFeedback;

typedef boost::shared_ptr< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback > FollowCartesianTrajectoryFeedbackPtr;
typedef boost::shared_ptr< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback const> FollowCartesianTrajectoryFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator1> & lhs, const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.controlled_frame == rhs.controlled_frame &&
    lhs.desired == rhs.desired &&
    lhs.actual == rhs.actual &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator1> & lhs, const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cartesian_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f58bb97e9d51288ac02f719ac397cb6e";
  }

  static const char* value(const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf58bb97e9d51288aULL;
  static const uint64_t static_value2 = 0xc02f719ac397cb6eULL;
};

template<class ContainerAllocator>
struct DataType< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartesian_control_msgs/FollowCartesianTrajectoryFeedback";
  }

  static const char* value(const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"string controlled_frame\n"
"CartesianTrajectoryPoint desired\n"
"CartesianTrajectoryPoint actual\n"
"CartesianTrajectoryPoint error\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cartesian_control_msgs/CartesianTrajectoryPoint\n"
"duration time_from_start\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist twist\n"
"geometry_msgs/Accel acceleration\n"
"# A more suitable datatype would be good, see https://github.com/ros/common_msgs/issues/137\n"
"geometry_msgs/Accel jerk\n"
"CartesianPosture posture\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: cartesian_control_msgs/CartesianPosture\n"
"# Posture joint names may reflect a subset of all available joints (empty posture definitions are\n"
"# also possible). The length of posture_joint_names and posture_joint_values have to be equal.\n"
"\n"
"string[] posture_joint_names\n"
"float64[] posture_joint_values\n"
;
  }

  static const char* value(const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.controlled_frame);
      stream.next(m.desired);
      stream.next(m.actual);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowCartesianTrajectoryFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartesian_control_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "controlled_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.controlled_frame);
    s << indent << "desired: ";
    s << std::endl;
    Printer< ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.desired);
    s << indent << "actual: ";
    s << std::endl;
    Printer< ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.actual);
    s << indent << "error: ";
    s << std::endl;
    Printer< ::cartesian_control_msgs::CartesianTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTESIAN_CONTROL_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYFEEDBACK_H
