# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cartesian_control_msgs/FollowCartesianTrajectoryActionFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import actionlib_msgs.msg
import cartesian_control_msgs.msg
import genpy
import geometry_msgs.msg
import std_msgs.msg

class FollowCartesianTrajectoryActionFeedback(genpy.Message):
  _md5sum = "1c281a744dcc601ff50dc256c9acc003"
  _type = "cartesian_control_msgs/FollowCartesianTrajectoryActionFeedback"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
FollowCartesianTrajectoryFeedback feedback

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: actionlib_msgs/GoalStatus
GoalID goal_id
uint8 status
uint8 PENDING         = 0   # The goal has yet to be processed by the action server
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                            #   and has since completed its execution (Terminal State)
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                            #    to some failure (Terminal State)
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                            #    because the goal was unattainable or invalid (Terminal State)
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                            #    and has not yet completed execution
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                            #    but the action server has not yet confirmed that the goal is canceled
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                            #    and was successfully cancelled (Terminal State)
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                            #    sent over the wire by an action server

#Allow for the user to associate a string with GoalStatus for debugging
string text


================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: cartesian_control_msgs/FollowCartesianTrajectoryFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
string controlled_frame
CartesianTrajectoryPoint desired
CartesianTrajectoryPoint actual
CartesianTrajectoryPoint error


================================================================================
MSG: cartesian_control_msgs/CartesianTrajectoryPoint
duration time_from_start
geometry_msgs/Pose pose
geometry_msgs/Twist twist
geometry_msgs/Accel acceleration
# A more suitable datatype would be good, see https://github.com/ros/common_msgs/issues/137
geometry_msgs/Accel jerk
CartesianPosture posture

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: cartesian_control_msgs/CartesianPosture
# Posture joint names may reflect a subset of all available joints (empty posture definitions are
# also possible). The length of posture_joint_names and posture_joint_values have to be equal.

string[] posture_joint_names
float64[] posture_joint_values
"""
  __slots__ = ['header','status','feedback']
  _slot_types = ['std_msgs/Header','actionlib_msgs/GoalStatus','cartesian_control_msgs/FollowCartesianTrajectoryFeedback']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,status,feedback

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FollowCartesianTrajectoryActionFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.status is None:
        self.status = actionlib_msgs.msg.GoalStatus()
      if self.feedback is None:
        self.feedback = cartesian_control_msgs.msg.FollowCartesianTrajectoryFeedback()
    else:
      self.header = std_msgs.msg.Header()
      self.status = actionlib_msgs.msg.GoalStatus()
      self.feedback = cartesian_control_msgs.msg.FollowCartesianTrajectoryFeedback()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.status.goal_id.stamp.secs, _x.status.goal_id.stamp.nsecs))
      _x = self.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.feedback.header.seq, _x.feedback.header.stamp.secs, _x.feedback.header.stamp.nsecs))
      _x = self.feedback.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.feedback.controlled_frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i25d().pack(_x.feedback.desired.time_from_start.secs, _x.feedback.desired.time_from_start.nsecs, _x.feedback.desired.pose.position.x, _x.feedback.desired.pose.position.y, _x.feedback.desired.pose.position.z, _x.feedback.desired.pose.orientation.x, _x.feedback.desired.pose.orientation.y, _x.feedback.desired.pose.orientation.z, _x.feedback.desired.pose.orientation.w, _x.feedback.desired.twist.linear.x, _x.feedback.desired.twist.linear.y, _x.feedback.desired.twist.linear.z, _x.feedback.desired.twist.angular.x, _x.feedback.desired.twist.angular.y, _x.feedback.desired.twist.angular.z, _x.feedback.desired.acceleration.linear.x, _x.feedback.desired.acceleration.linear.y, _x.feedback.desired.acceleration.linear.z, _x.feedback.desired.acceleration.angular.x, _x.feedback.desired.acceleration.angular.y, _x.feedback.desired.acceleration.angular.z, _x.feedback.desired.jerk.linear.x, _x.feedback.desired.jerk.linear.y, _x.feedback.desired.jerk.linear.z, _x.feedback.desired.jerk.angular.x, _x.feedback.desired.jerk.angular.y, _x.feedback.desired.jerk.angular.z))
      length = len(self.feedback.desired.posture.posture_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.feedback.desired.posture.posture_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.feedback.desired.posture.posture_joint_values)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.feedback.desired.posture.posture_joint_values))
      _x = self
      buff.write(_get_struct_2i25d().pack(_x.feedback.actual.time_from_start.secs, _x.feedback.actual.time_from_start.nsecs, _x.feedback.actual.pose.position.x, _x.feedback.actual.pose.position.y, _x.feedback.actual.pose.position.z, _x.feedback.actual.pose.orientation.x, _x.feedback.actual.pose.orientation.y, _x.feedback.actual.pose.orientation.z, _x.feedback.actual.pose.orientation.w, _x.feedback.actual.twist.linear.x, _x.feedback.actual.twist.linear.y, _x.feedback.actual.twist.linear.z, _x.feedback.actual.twist.angular.x, _x.feedback.actual.twist.angular.y, _x.feedback.actual.twist.angular.z, _x.feedback.actual.acceleration.linear.x, _x.feedback.actual.acceleration.linear.y, _x.feedback.actual.acceleration.linear.z, _x.feedback.actual.acceleration.angular.x, _x.feedback.actual.acceleration.angular.y, _x.feedback.actual.acceleration.angular.z, _x.feedback.actual.jerk.linear.x, _x.feedback.actual.jerk.linear.y, _x.feedback.actual.jerk.linear.z, _x.feedback.actual.jerk.angular.x, _x.feedback.actual.jerk.angular.y, _x.feedback.actual.jerk.angular.z))
      length = len(self.feedback.actual.posture.posture_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.feedback.actual.posture.posture_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.feedback.actual.posture.posture_joint_values)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.feedback.actual.posture.posture_joint_values))
      _x = self
      buff.write(_get_struct_2i25d().pack(_x.feedback.error.time_from_start.secs, _x.feedback.error.time_from_start.nsecs, _x.feedback.error.pose.position.x, _x.feedback.error.pose.position.y, _x.feedback.error.pose.position.z, _x.feedback.error.pose.orientation.x, _x.feedback.error.pose.orientation.y, _x.feedback.error.pose.orientation.z, _x.feedback.error.pose.orientation.w, _x.feedback.error.twist.linear.x, _x.feedback.error.twist.linear.y, _x.feedback.error.twist.linear.z, _x.feedback.error.twist.angular.x, _x.feedback.error.twist.angular.y, _x.feedback.error.twist.angular.z, _x.feedback.error.acceleration.linear.x, _x.feedback.error.acceleration.linear.y, _x.feedback.error.acceleration.linear.z, _x.feedback.error.acceleration.angular.x, _x.feedback.error.acceleration.angular.y, _x.feedback.error.acceleration.angular.z, _x.feedback.error.jerk.linear.x, _x.feedback.error.jerk.linear.y, _x.feedback.error.jerk.linear.z, _x.feedback.error.jerk.angular.x, _x.feedback.error.jerk.angular.y, _x.feedback.error.jerk.angular.z))
      length = len(self.feedback.error.posture.posture_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.feedback.error.posture.posture_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.feedback.error.posture.posture_joint_values)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.feedback.error.posture.posture_joint_values))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.status is None:
        self.status = actionlib_msgs.msg.GoalStatus()
      if self.feedback is None:
        self.feedback = cartesian_control_msgs.msg.FollowCartesianTrajectoryFeedback()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.status.goal_id.stamp.secs, _x.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.text = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.feedback.header.seq, _x.feedback.header.stamp.secs, _x.feedback.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedback.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedback.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedback.controlled_frame = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedback.controlled_frame = str[start:end]
      _x = self
      start = end
      end += 208
      (_x.feedback.desired.time_from_start.secs, _x.feedback.desired.time_from_start.nsecs, _x.feedback.desired.pose.position.x, _x.feedback.desired.pose.position.y, _x.feedback.desired.pose.position.z, _x.feedback.desired.pose.orientation.x, _x.feedback.desired.pose.orientation.y, _x.feedback.desired.pose.orientation.z, _x.feedback.desired.pose.orientation.w, _x.feedback.desired.twist.linear.x, _x.feedback.desired.twist.linear.y, _x.feedback.desired.twist.linear.z, _x.feedback.desired.twist.angular.x, _x.feedback.desired.twist.angular.y, _x.feedback.desired.twist.angular.z, _x.feedback.desired.acceleration.linear.x, _x.feedback.desired.acceleration.linear.y, _x.feedback.desired.acceleration.linear.z, _x.feedback.desired.acceleration.angular.x, _x.feedback.desired.acceleration.angular.y, _x.feedback.desired.acceleration.angular.z, _x.feedback.desired.jerk.linear.x, _x.feedback.desired.jerk.linear.y, _x.feedback.desired.jerk.linear.z, _x.feedback.desired.jerk.angular.x, _x.feedback.desired.jerk.angular.y, _x.feedback.desired.jerk.angular.z,) = _get_struct_2i25d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feedback.desired.posture.posture_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.feedback.desired.posture.posture_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.feedback.desired.posture.posture_joint_values = s.unpack(str[start:end])
      _x = self
      start = end
      end += 208
      (_x.feedback.actual.time_from_start.secs, _x.feedback.actual.time_from_start.nsecs, _x.feedback.actual.pose.position.x, _x.feedback.actual.pose.position.y, _x.feedback.actual.pose.position.z, _x.feedback.actual.pose.orientation.x, _x.feedback.actual.pose.orientation.y, _x.feedback.actual.pose.orientation.z, _x.feedback.actual.pose.orientation.w, _x.feedback.actual.twist.linear.x, _x.feedback.actual.twist.linear.y, _x.feedback.actual.twist.linear.z, _x.feedback.actual.twist.angular.x, _x.feedback.actual.twist.angular.y, _x.feedback.actual.twist.angular.z, _x.feedback.actual.acceleration.linear.x, _x.feedback.actual.acceleration.linear.y, _x.feedback.actual.acceleration.linear.z, _x.feedback.actual.acceleration.angular.x, _x.feedback.actual.acceleration.angular.y, _x.feedback.actual.acceleration.angular.z, _x.feedback.actual.jerk.linear.x, _x.feedback.actual.jerk.linear.y, _x.feedback.actual.jerk.linear.z, _x.feedback.actual.jerk.angular.x, _x.feedback.actual.jerk.angular.y, _x.feedback.actual.jerk.angular.z,) = _get_struct_2i25d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feedback.actual.posture.posture_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.feedback.actual.posture.posture_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.feedback.actual.posture.posture_joint_values = s.unpack(str[start:end])
      _x = self
      start = end
      end += 208
      (_x.feedback.error.time_from_start.secs, _x.feedback.error.time_from_start.nsecs, _x.feedback.error.pose.position.x, _x.feedback.error.pose.position.y, _x.feedback.error.pose.position.z, _x.feedback.error.pose.orientation.x, _x.feedback.error.pose.orientation.y, _x.feedback.error.pose.orientation.z, _x.feedback.error.pose.orientation.w, _x.feedback.error.twist.linear.x, _x.feedback.error.twist.linear.y, _x.feedback.error.twist.linear.z, _x.feedback.error.twist.angular.x, _x.feedback.error.twist.angular.y, _x.feedback.error.twist.angular.z, _x.feedback.error.acceleration.linear.x, _x.feedback.error.acceleration.linear.y, _x.feedback.error.acceleration.linear.z, _x.feedback.error.acceleration.angular.x, _x.feedback.error.acceleration.angular.y, _x.feedback.error.acceleration.angular.z, _x.feedback.error.jerk.linear.x, _x.feedback.error.jerk.linear.y, _x.feedback.error.jerk.linear.z, _x.feedback.error.jerk.angular.x, _x.feedback.error.jerk.angular.y, _x.feedback.error.jerk.angular.z,) = _get_struct_2i25d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feedback.error.posture.posture_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.feedback.error.posture.posture_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.feedback.error.posture.posture_joint_values = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.status.goal_id.stamp.secs, _x.status.goal_id.stamp.nsecs))
      _x = self.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.feedback.header.seq, _x.feedback.header.stamp.secs, _x.feedback.header.stamp.nsecs))
      _x = self.feedback.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.feedback.controlled_frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i25d().pack(_x.feedback.desired.time_from_start.secs, _x.feedback.desired.time_from_start.nsecs, _x.feedback.desired.pose.position.x, _x.feedback.desired.pose.position.y, _x.feedback.desired.pose.position.z, _x.feedback.desired.pose.orientation.x, _x.feedback.desired.pose.orientation.y, _x.feedback.desired.pose.orientation.z, _x.feedback.desired.pose.orientation.w, _x.feedback.desired.twist.linear.x, _x.feedback.desired.twist.linear.y, _x.feedback.desired.twist.linear.z, _x.feedback.desired.twist.angular.x, _x.feedback.desired.twist.angular.y, _x.feedback.desired.twist.angular.z, _x.feedback.desired.acceleration.linear.x, _x.feedback.desired.acceleration.linear.y, _x.feedback.desired.acceleration.linear.z, _x.feedback.desired.acceleration.angular.x, _x.feedback.desired.acceleration.angular.y, _x.feedback.desired.acceleration.angular.z, _x.feedback.desired.jerk.linear.x, _x.feedback.desired.jerk.linear.y, _x.feedback.desired.jerk.linear.z, _x.feedback.desired.jerk.angular.x, _x.feedback.desired.jerk.angular.y, _x.feedback.desired.jerk.angular.z))
      length = len(self.feedback.desired.posture.posture_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.feedback.desired.posture.posture_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.feedback.desired.posture.posture_joint_values)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.feedback.desired.posture.posture_joint_values.tostring())
      _x = self
      buff.write(_get_struct_2i25d().pack(_x.feedback.actual.time_from_start.secs, _x.feedback.actual.time_from_start.nsecs, _x.feedback.actual.pose.position.x, _x.feedback.actual.pose.position.y, _x.feedback.actual.pose.position.z, _x.feedback.actual.pose.orientation.x, _x.feedback.actual.pose.orientation.y, _x.feedback.actual.pose.orientation.z, _x.feedback.actual.pose.orientation.w, _x.feedback.actual.twist.linear.x, _x.feedback.actual.twist.linear.y, _x.feedback.actual.twist.linear.z, _x.feedback.actual.twist.angular.x, _x.feedback.actual.twist.angular.y, _x.feedback.actual.twist.angular.z, _x.feedback.actual.acceleration.linear.x, _x.feedback.actual.acceleration.linear.y, _x.feedback.actual.acceleration.linear.z, _x.feedback.actual.acceleration.angular.x, _x.feedback.actual.acceleration.angular.y, _x.feedback.actual.acceleration.angular.z, _x.feedback.actual.jerk.linear.x, _x.feedback.actual.jerk.linear.y, _x.feedback.actual.jerk.linear.z, _x.feedback.actual.jerk.angular.x, _x.feedback.actual.jerk.angular.y, _x.feedback.actual.jerk.angular.z))
      length = len(self.feedback.actual.posture.posture_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.feedback.actual.posture.posture_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.feedback.actual.posture.posture_joint_values)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.feedback.actual.posture.posture_joint_values.tostring())
      _x = self
      buff.write(_get_struct_2i25d().pack(_x.feedback.error.time_from_start.secs, _x.feedback.error.time_from_start.nsecs, _x.feedback.error.pose.position.x, _x.feedback.error.pose.position.y, _x.feedback.error.pose.position.z, _x.feedback.error.pose.orientation.x, _x.feedback.error.pose.orientation.y, _x.feedback.error.pose.orientation.z, _x.feedback.error.pose.orientation.w, _x.feedback.error.twist.linear.x, _x.feedback.error.twist.linear.y, _x.feedback.error.twist.linear.z, _x.feedback.error.twist.angular.x, _x.feedback.error.twist.angular.y, _x.feedback.error.twist.angular.z, _x.feedback.error.acceleration.linear.x, _x.feedback.error.acceleration.linear.y, _x.feedback.error.acceleration.linear.z, _x.feedback.error.acceleration.angular.x, _x.feedback.error.acceleration.angular.y, _x.feedback.error.acceleration.angular.z, _x.feedback.error.jerk.linear.x, _x.feedback.error.jerk.linear.y, _x.feedback.error.jerk.linear.z, _x.feedback.error.jerk.angular.x, _x.feedback.error.jerk.angular.y, _x.feedback.error.jerk.angular.z))
      length = len(self.feedback.error.posture.posture_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.feedback.error.posture.posture_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.feedback.error.posture.posture_joint_values)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.feedback.error.posture.posture_joint_values.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.status is None:
        self.status = actionlib_msgs.msg.GoalStatus()
      if self.feedback is None:
        self.feedback = cartesian_control_msgs.msg.FollowCartesianTrajectoryFeedback()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.status.goal_id.stamp.secs, _x.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.text = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.feedback.header.seq, _x.feedback.header.stamp.secs, _x.feedback.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedback.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedback.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedback.controlled_frame = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedback.controlled_frame = str[start:end]
      _x = self
      start = end
      end += 208
      (_x.feedback.desired.time_from_start.secs, _x.feedback.desired.time_from_start.nsecs, _x.feedback.desired.pose.position.x, _x.feedback.desired.pose.position.y, _x.feedback.desired.pose.position.z, _x.feedback.desired.pose.orientation.x, _x.feedback.desired.pose.orientation.y, _x.feedback.desired.pose.orientation.z, _x.feedback.desired.pose.orientation.w, _x.feedback.desired.twist.linear.x, _x.feedback.desired.twist.linear.y, _x.feedback.desired.twist.linear.z, _x.feedback.desired.twist.angular.x, _x.feedback.desired.twist.angular.y, _x.feedback.desired.twist.angular.z, _x.feedback.desired.acceleration.linear.x, _x.feedback.desired.acceleration.linear.y, _x.feedback.desired.acceleration.linear.z, _x.feedback.desired.acceleration.angular.x, _x.feedback.desired.acceleration.angular.y, _x.feedback.desired.acceleration.angular.z, _x.feedback.desired.jerk.linear.x, _x.feedback.desired.jerk.linear.y, _x.feedback.desired.jerk.linear.z, _x.feedback.desired.jerk.angular.x, _x.feedback.desired.jerk.angular.y, _x.feedback.desired.jerk.angular.z,) = _get_struct_2i25d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feedback.desired.posture.posture_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.feedback.desired.posture.posture_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.feedback.desired.posture.posture_joint_values = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 208
      (_x.feedback.actual.time_from_start.secs, _x.feedback.actual.time_from_start.nsecs, _x.feedback.actual.pose.position.x, _x.feedback.actual.pose.position.y, _x.feedback.actual.pose.position.z, _x.feedback.actual.pose.orientation.x, _x.feedback.actual.pose.orientation.y, _x.feedback.actual.pose.orientation.z, _x.feedback.actual.pose.orientation.w, _x.feedback.actual.twist.linear.x, _x.feedback.actual.twist.linear.y, _x.feedback.actual.twist.linear.z, _x.feedback.actual.twist.angular.x, _x.feedback.actual.twist.angular.y, _x.feedback.actual.twist.angular.z, _x.feedback.actual.acceleration.linear.x, _x.feedback.actual.acceleration.linear.y, _x.feedback.actual.acceleration.linear.z, _x.feedback.actual.acceleration.angular.x, _x.feedback.actual.acceleration.angular.y, _x.feedback.actual.acceleration.angular.z, _x.feedback.actual.jerk.linear.x, _x.feedback.actual.jerk.linear.y, _x.feedback.actual.jerk.linear.z, _x.feedback.actual.jerk.angular.x, _x.feedback.actual.jerk.angular.y, _x.feedback.actual.jerk.angular.z,) = _get_struct_2i25d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feedback.actual.posture.posture_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.feedback.actual.posture.posture_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.feedback.actual.posture.posture_joint_values = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 208
      (_x.feedback.error.time_from_start.secs, _x.feedback.error.time_from_start.nsecs, _x.feedback.error.pose.position.x, _x.feedback.error.pose.position.y, _x.feedback.error.pose.position.z, _x.feedback.error.pose.orientation.x, _x.feedback.error.pose.orientation.y, _x.feedback.error.pose.orientation.z, _x.feedback.error.pose.orientation.w, _x.feedback.error.twist.linear.x, _x.feedback.error.twist.linear.y, _x.feedback.error.twist.linear.z, _x.feedback.error.twist.angular.x, _x.feedback.error.twist.angular.y, _x.feedback.error.twist.angular.z, _x.feedback.error.acceleration.linear.x, _x.feedback.error.acceleration.linear.y, _x.feedback.error.acceleration.linear.z, _x.feedback.error.acceleration.angular.x, _x.feedback.error.acceleration.angular.y, _x.feedback.error.acceleration.angular.z, _x.feedback.error.jerk.linear.x, _x.feedback.error.jerk.linear.y, _x.feedback.error.jerk.linear.z, _x.feedback.error.jerk.angular.x, _x.feedback.error.jerk.angular.y, _x.feedback.error.jerk.angular.z,) = _get_struct_2i25d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feedback.error.posture.posture_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.feedback.error.posture.posture_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.feedback.error.posture.posture_joint_values = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2i25d = None
def _get_struct_2i25d():
    global _struct_2i25d
    if _struct_2i25d is None:
        _struct_2i25d = struct.Struct("<2i25d")
    return _struct_2i25d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
