// Auto-generated. Do not edit!

// (in-package cartesian_control_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let CartesianTrajectoryPoint = require('./CartesianTrajectoryPoint.js');
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class FollowCartesianTrajectoryFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.header = null;
      this.controlled_frame = null;
      this.desired = null;
      this.actual = null;
      this.error = null;
    }
    else {
      if (initObj.hasOwnProperty('header')) {
        this.header = initObj.header
      }
      else {
        this.header = new std_msgs.msg.Header();
      }
      if (initObj.hasOwnProperty('controlled_frame')) {
        this.controlled_frame = initObj.controlled_frame
      }
      else {
        this.controlled_frame = '';
      }
      if (initObj.hasOwnProperty('desired')) {
        this.desired = initObj.desired
      }
      else {
        this.desired = new CartesianTrajectoryPoint();
      }
      if (initObj.hasOwnProperty('actual')) {
        this.actual = initObj.actual
      }
      else {
        this.actual = new CartesianTrajectoryPoint();
      }
      if (initObj.hasOwnProperty('error')) {
        this.error = initObj.error
      }
      else {
        this.error = new CartesianTrajectoryPoint();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FollowCartesianTrajectoryFeedback
    // Serialize message field [header]
    bufferOffset = std_msgs.msg.Header.serialize(obj.header, buffer, bufferOffset);
    // Serialize message field [controlled_frame]
    bufferOffset = _serializer.string(obj.controlled_frame, buffer, bufferOffset);
    // Serialize message field [desired]
    bufferOffset = CartesianTrajectoryPoint.serialize(obj.desired, buffer, bufferOffset);
    // Serialize message field [actual]
    bufferOffset = CartesianTrajectoryPoint.serialize(obj.actual, buffer, bufferOffset);
    // Serialize message field [error]
    bufferOffset = CartesianTrajectoryPoint.serialize(obj.error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FollowCartesianTrajectoryFeedback
    let len;
    let data = new FollowCartesianTrajectoryFeedback(null);
    // Deserialize message field [header]
    data.header = std_msgs.msg.Header.deserialize(buffer, bufferOffset);
    // Deserialize message field [controlled_frame]
    data.controlled_frame = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [desired]
    data.desired = CartesianTrajectoryPoint.deserialize(buffer, bufferOffset);
    // Deserialize message field [actual]
    data.actual = CartesianTrajectoryPoint.deserialize(buffer, bufferOffset);
    // Deserialize message field [error]
    data.error = CartesianTrajectoryPoint.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.Header.getMessageSize(object.header);
    length += _getByteLength(object.controlled_frame);
    length += CartesianTrajectoryPoint.getMessageSize(object.desired);
    length += CartesianTrajectoryPoint.getMessageSize(object.actual);
    length += CartesianTrajectoryPoint.getMessageSize(object.error);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'cartesian_control_msgs/FollowCartesianTrajectoryFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f58bb97e9d51288ac02f719ac397cb6e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    string controlled_frame
    CartesianTrajectoryPoint desired
    CartesianTrajectoryPoint actual
    CartesianTrajectoryPoint error
    
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: cartesian_control_msgs/CartesianTrajectoryPoint
    duration time_from_start
    geometry_msgs/Pose pose
    geometry_msgs/Twist twist
    geometry_msgs/Accel acceleration
    # A more suitable datatype would be good, see https://github.com/ros/common_msgs/issues/137
    geometry_msgs/Accel jerk
    CartesianPosture posture
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: geometry_msgs/Twist
    # This expresses velocity in free space broken into its linear and angular parts.
    Vector3  linear
    Vector3  angular
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    ================================================================================
    MSG: geometry_msgs/Accel
    # This expresses acceleration in free space broken into its linear and angular parts.
    Vector3  linear
    Vector3  angular
    
    ================================================================================
    MSG: cartesian_control_msgs/CartesianPosture
    # Posture joint names may reflect a subset of all available joints (empty posture definitions are
    # also possible). The length of posture_joint_names and posture_joint_values have to be equal.
    
    string[] posture_joint_names
    float64[] posture_joint_values
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FollowCartesianTrajectoryFeedback(null);
    if (msg.header !== undefined) {
      resolved.header = std_msgs.msg.Header.Resolve(msg.header)
    }
    else {
      resolved.header = new std_msgs.msg.Header()
    }

    if (msg.controlled_frame !== undefined) {
      resolved.controlled_frame = msg.controlled_frame;
    }
    else {
      resolved.controlled_frame = ''
    }

    if (msg.desired !== undefined) {
      resolved.desired = CartesianTrajectoryPoint.Resolve(msg.desired)
    }
    else {
      resolved.desired = new CartesianTrajectoryPoint()
    }

    if (msg.actual !== undefined) {
      resolved.actual = CartesianTrajectoryPoint.Resolve(msg.actual)
    }
    else {
      resolved.actual = new CartesianTrajectoryPoint()
    }

    if (msg.error !== undefined) {
      resolved.error = CartesianTrajectoryPoint.Resolve(msg.error)
    }
    else {
      resolved.error = new CartesianTrajectoryPoint()
    }

    return resolved;
    }
};

module.exports = FollowCartesianTrajectoryFeedback;
